### ISSUE TITLE
error at create painterCtors

### ISSUE THREAD

**Issue by vcc0827** [ecomfe/zrender#1004]
开发环境下正常使用，打包部署到线上时，该行代码报错 var painter = new painterCtors[rendererType](dom, storage, opts, id);
错误代码：Uncaught TypeError: Ft[s] is not a constructor  （zrender.js:69 ）
请问是项目执行打包的时候没有正确打包文件吗？

**Comment by plainheart** [comment]
请参考这里 https://github.com/ecomfe/zrender/issues/981#issuecomment-1343864170。大概是因为没有显式导入渲染器，以至于 build 的时候被 tree-shaked 了。

**Comment by vcc0827** [comment]
还是报错：
```
Uncaught TypeError: Ft[s] is not a constructor (zrender.js:68)
    at new t (zrender.js:68:19)
    at Object.Ut (zrender.js:247:12)
    at zd.s (index.vue:209:1)
    at ga.ob (getscript?v=3.0&ak=eZNBZlBzG2VuTGHYy8HSSD3PYfhR7ELA&services=&t=20230317105246:1:132329)
    at getscript?v=3.0&ak=eZNBZlBzG2VuTGHYy8HSSD3PYfhR7ELA&services=&t=20230317105246:1:132120
```
根据官方文档，我在入口的index.html上添加了  
```
<script language="javascript" src="../../staic/zrender/zrender.js"></script> 
<script language="javascript" src="../../staic/zrender/zrender.min.js"></script>
```
指向本地存放的zrender.js和zrender.min.js
