### ISSUE TITLE
build后在线上环境报错

### ISSUE THREAD

**Issue by vcc0827** [ecomfe/zrender#1007]
控制台报错：
```
Uncaught TypeError: Ft[s] is not a constructor (zrender.js:68)
    at new t (zrender.js:68:19)
    at Object.Ut (zrender.js:247:12)
    at zd.s (index.vue:209:1)
    at ga.ob (getscript?v=3.0&ak=eZNBZlBzG2VuTGHYy8HSSD3PYfhR7ELA&services=&t=20230317105246:1:132329)
    at getscript?v=3.0&ak=eZNBZlBzG2VuTGHYy8HSSD3PYfhR7ELA&services=&t=20230317105246:1:132120
```
根据官方文档，我在入口的index.html上添加了  
```
<script language="javascript" src="../../staic/zrender/zrender.js"></script> 
<script language="javascript" src="../../staic/zrender/zrender.min.js"></script>
```
指向本地存放的zrender.js和zrender.min.js
然后也在使用zrender的vue文件中进行了引用
```
import * as zrender from 'zrender'
```
但是仍然报错，打印报错指向的源码发现这里
```
    var painter = new painterCtors[rendererType](dom, storage, opts, id);

    var ssrMode = opts.ssr || painter.ssrOnly;
```
opts上没有ssr属性，painter上也没有ssrOnly属性。
求大佬指教怎么正确地发布到线上使用

**Comment by vcc0827** [comment]
把文件中的 
```
import * as zrender from 'zrender'
```
替换成
```
import * as zrender from "zrender/dist/zrender";
```
问题就解决了。
猜测可能是因为build之后zrender引用的位置发生了变化？
