### ISSUE TITLE
ERROR in ./node_modules/zrender/lib/core/BoundingRect.js

### ISSUE THREAD

**Issue by ciukstar** [ecomfe/zrender#355]
Hi. I use **Angular 6** and **Angular CLI** for my project. Aside from `echarts@4.1.0`, `@types/echarts@0.0.13` and `echarts-gl@1.1.1`, my project has other dependencies. Yet, I keep getting only `zrender` related errors on `ng build --prod`. Is there a way to fix this error? The error does not arise on `ng build` (dev mode, not prod).
Below is then Angular version (`@latest`) as result of `ng -v` command:
```
ngular CLI: 6.0.8
Node: 10.0.0
OS: linux x64
Angular: 6.0.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.3.1
@angular/cli                      6.0.8
@angular/material                 6.3.1
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3
```
Below is the result of trying to `sergiu@ub:arm-analytics-spb$ ng build --prod`:
```
Date: 2018-06-29T14:12:35.049Z
Hash: 50f0e8cd356c2ed65900
Time: 246070ms
chunk {scripts} scripts.542fa1665ab6f03f5606.js (scripts) 1.94 MB  [rendered]
chunk {0} runtime.a66f828dca56eeb90e02.js (runtime) 1.05 kB [entry] [rendered]
chunk {1} styles.ea5c8ea836283ab907af.css (styles) 561 kB [initial] [rendered]
chunk {2} polyfills.c3fc30f809a974dee0e5.js (polyfills) 59.6 kB [initial] [rendered]
chunk {3} main.8d35cc14bfbe012fa4e6.js (main) 6.66 MB [initial] [rendered]

ERROR in ./node_modules/zrender/lib/core/BoundingRect.js
Module build failed: TypeError: Cannot read property 'kind' of undefined
    at isObjectOrObjectArrayTypeReference (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:20709:34)
    at parseNestedTypeLiteral (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:20748:43)
    at parseParameterOrPropertyTag (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:20733:85)
    at parseTag (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:20572:40)
    at /home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:20447:44
    at Object.scanRange (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:8611:26)
    at parseJSDocCommentWorker (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:20419:25)
    at Object.parseJSDocComment (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:20373:31)
    at addJSDocComment (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:15579:68)
    at createNodeWithJSDoc (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:15906:17)
    at parseObjectLiteralElement (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:18930:24)
    at parseListElement (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16289:20)
    at parseDelimitedList (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16574:31)
    at parseObjectLiteralExpression (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:18979:31)
    at parsePrimaryExpression (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:18872:28)
    at parseMemberExpressionOrHigher (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:18445:30)
ERROR in ./node_modules/echarts/lib/coord/geo/Region.js
Module build failed: TypeError: Cannot read property 'kind' of undefined
    at isObjectOrObjectArrayTypeReference (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:20709:34)
    at parseNestedTypeLiteral (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:20748:43)
    at parseParameterOrPropertyTag (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:20733:85)
    at parseTag (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:20572:40)
    at /home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:20447:44
    at Object.scanRange (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:8611:26)
    at parseJSDocCommentWorker (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:20419:25)
    at Object.parseJSDocComment (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:20373:31)
    at addJSDocComment (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:15579:68)
    at createNodeWithJSDoc (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:15906:17)
    at parseObjectLiteralElement (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:18930:24)
    at parseListElement (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16289:20)
    at parseDelimitedList (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16574:31)
    at parseObjectLiteralExpression (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:18979:31)
    at parsePrimaryExpression (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:18872:28)
    at parseMemberExpressionOrHigher (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:18445:30)
ERROR in ./node_modules/echarts/lib/data/Tree.js
Module build failed: TypeError: Cannot read property 'kind' of undefined
    at isObjectOrObjectArrayTypeReference (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:20709:34)
    at parseNestedTypeLiteral (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:20748:43)
    at parseParameterOrPropertyTag (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:20733:85)
    at parseTag (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:20572:40)
    at /home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:20447:44
    at Object.scanRange (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:8611:26)
    at parseJSDocCommentWorker (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:20419:25)
    at Object.parseJSDocComment (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:20373:31)
    at addJSDocComment (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:15579:68)
    at createNodeWithJSDoc (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:15906:17)
    at parseStatement (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:19455:53)
    at parseListElement (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16289:20)
    at parseList (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16273:35)
    at parseSourceFileWorker (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:15558:37)
    at Object.parseSourceFile (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:15429:26)
    at Object.createSourceFile (/home/sergiu/Workspaces/arm-analytics-spb/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:15260:29)

```

**Comment by ciukstar** [comment]
Problem gone after updating to `Angular 6.1.0` and `typescript 2.9.2`
